backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: folder-name
    label: Collection Label
    folder: static/folder-name
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Post Image, widget: image }
      - { name: body, label: Body, widget: markdown }